# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_auto_20161130_0157"),
        ("bike", "0001_bike_with_fsm"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="purchased_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchased_bike",
                to="registration.Member",
            ),
        ),
        migrations.AlterField(
            model_name="bike",
            name="claimed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claimed_bike",
                to="registration.Member",
            ),
        ),
    ]
