# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bike", "0005_auto_20170202_0345"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="donated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
