version: "2"
services:
#  nginx:
#    build:
#      context: docker/nginx
#    image: bcbc/nginx:production
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes_from:
#      - workstand:ro
#    volumes:
#      - certs:/etc/letsencrypt
#    restart: always
#    networks:
#      - default
#    links:
#      - workstand
  workstand:
    build:
      context: .
      dockerfile: Dockerfile
    image: bcbc/workstand:production
    command: 'bash /code/entrypoint-interface.sh'
    environment:
      - DJANGO_SETTINGS_MODULE=bikeshop.settings.production
      - PYTHONUNBUFFERED=TRUE
    ports:
      - "8000:8000"
    volumes:
      - static:/code/static
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: bcbc/workstand:production
    command: 'bash /code/entrypoint-worker.sh'
    environment:
      - DJANGO_SETTINGS_MODULE=bikeshop.settings.production
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - static:/code/static
  redis:
    restart: always
  db:
    restart: always

volumes:
  static:
    external: false
  certs:
    external: false
