version: "2"
services:
  workstand:
    networks:
      - default
    image: bcbc/workstand
    links:
      - redis
      - db
  redis:
    networks:
      - default
    image: redis:latest
  db:
    networks:
      - default
    image: postgres:9.6
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
    external: false

networks:
  default:
    driver: bridge
