# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20170101_2054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("VOLUNTEER", "volunteer"),
                    ("FIX", "fix bike"),
                    ("BUILD", "build bike"),
                    ("WORKSHOP", "workshop"),
                    ("VISIT", "visit"),
                    ("DONATE", "donate"),
                    ("STAFF", "staff"),
                ],
                max_length=50,
            ),
        ),
    ]
