# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-02 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170219_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('NONE', 'None'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('VOLUNTEERING', 'Volunteering'), ('SQUARE', 'Square'), ('PAYPAL', 'PayPal'), ('YOUTH', 'Youth'), ('UNKNOWN', 'Unknown')], default='NONE', max_length=12),
        ),
    ]
