- name: migrate app
  action: django_manage command=migrate app_path={{ app_dir }} settings={{ settings_module }} virtualenv={{ venv }}
  ignore_errors: yes
  environment:
    SECRET_KEY: "{{ django_key }}"
    DB_PASSWORD: "{{ db_user_password }}"


- name: collect static
  action: django_manage command="collectstatic --noinput" app_path={{ app_dir }} settings={{ settings_module }} virtualenv={{ venv }}
  ignore_errors: yes
  environment:
    SECRET_KEY: "{{ django_key }}"
    DB_PASSWORD: "{{ db_user_password }}"
