# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-26 21:59
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_auto_20170528_2339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="involvement",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("21cd9799b6", "General (receive email)"),
                    ("3a5a719017", "Volunteering"),
                    ("0ebb0b5468", "Events"),
                    ("84309225e7", "Workshops"),
                    ("c96d389517", "Shop"),
                ],
                max_length=54,
                null=True,
            ),
        ),
    ]
