# Generated by Django 2.2.9 on 2020-01-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20190526_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='preferred_pronoun',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
