# Generated by Django 2.2.9 on 2020-01-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_member_preferred_pronoun'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='self_identification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
