# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="email_consent",
            field=models.BooleanField(default=False),
        ),
    ]
