# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20161130_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
