# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-28 23:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_auto_20170518_0332"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="involvement",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("ac6922146d", "General (receive email)"),
                    ("3a5a719017", "Volunteering"),
                    ("0ebb0b5468", "Events"),
                    ("84309225e7", "Workshops"),
                    ("c96d389517", "Shop"),
                ],
                max_length=54,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
