# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_member_membership"),
    ]

    operations = [
        migrations.RemoveField(model_name="member", name="membership",),
    ]
