postgresql_postgis: yes
app_dir: "{{ webapps_dir }}/{{ app_name }}"

db_name: "{{ app_name }}_production"
db_user: "{{ app_name }}"

db_user_password: "{{ secret_db_user_password }}"
django_key: "{{ secret_django_key }}"

app_domain_name: shop.bcbc.bike
app_port: 9999
