# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='acknowledgement',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='community',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='safe_space',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='space',
        ),
    ]
