# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20160405_0354"),
        ("core", "0004_auto_20160410_1816"),
    ]

    operations = []
