# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='acknowledgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='community',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='safe_space',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='purpose',
            field=models.CharField(choices=[('VOLUNTEER', 'volunteer'), ('FIX', 'fix bike'), ('WORKSHOP', 'workshop'), ('VISIT', 'visit'), ('DONATE', 'donate'), ('STAFF', 'staff')], max_length=50),
        ),
    ]
