# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160410_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='acknowledgement',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='community',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='give_back',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='safe_space',
        ),
    ]
