# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160501_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='membership',
        ),
        migrations.AddField(
            model_name='membership',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Payment'),
        ),
    ]
