# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160526_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='member',
        ),
    ]
