# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160531_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.Membership'),
        ),
    ]
